---
# tasks file for kibana_install
- name: Install kibana packages
  ansible.builtin.apt:
    name: "kibana={{ kibana_version }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Hold kibana packages
  ansible.builtin.dpkg_selections:
    name: kibana
    selection: hold

- name: Configure kibana
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?server.port:', line: 'server.port: 5601' }
    - { regexp: '^#?server.host:', line: 'server.host: "0.0.0.0"' }
    - { regexp: '^#?server.publicBaseUrl:', line: 'server.publicBaseUrl: "http://{{ inventory_hostname }}:5601"' }
  notify: restart kibana